dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "nightly"  # nightly build
install:
  - pip install networkx
  - pip install mypy
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=network_simulator/
after_success:
  - coveralls
